apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: db-deployment
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: db
    template:
      metadata:
        labels:
          app: db
      spec:
        containers:
          - name: db
            image: pdgpires/ca4_p2_db:v1.0
            ports:
              - containerPort: 8082
              - containerPort: 9092
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: db-service
  spec:
    selector:
      app: db
    ports:
      - protocol: TCP
        port: 8082
        targetPort: 8082
      - protocol: TCP
        port: 9092
        targetPort: 9092
    type: ClusterIP