# Tomcat 10 with JDK 17
FROM tomcat:10-jdk17
# Copy the war file to the Tomcat webapps directory
COPY build/libs/react-and-spring-data-rest-basic-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/
# Expose the port 8080
EXPOSE 8080
