## Use the official Tomcat base image with JDK 21
FROM tomcat:10.1-jdk21

# Copy the Spring Boot WAR file to the Tomcat webapps directory
COPY CA2/part2/react-and-spring-data-rest-basic/build/libs/react-and-spring-data-rest-basic-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/

# Expose the default Tomcat port
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]